Player health
GameDevDojo/Cyberpunk2001 pull request #2
Opened 2018-04-18 16:26 UTC by Lefondesin

Dodany system śmierci i zdrowia (hp)

2018-04-18 16:27 UTC, Lefondesin commented
Seems legit

2018-04-18 18:46 UTC, noplisu requested changes

2018-04-18 18:46 UTC, noplisu commented on Assets/PlayerHealth.cs
> +
Zbędna pusta linia :)

2018-04-19 19:42 UTC, noplisu requested changes

2018-04-19 19:42 UTC, noplisu commented on Assets/PlayerHealth.cs
> +}
missing newline at the end of the file :D. There should be no unnecessary new lines in our files but git likes it that the files end with one new line :) so i suggest adding 1 new line.

2018-04-23 15:22 UTC, noplisu approved these changes

2018-04-23 15:22 UTC, merged